package interfaces;

import entidades.Aviso;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import logica.Consultas;

/**
 *
 * @author danagarces
 */
public class DifCultAvisosPanel extends javax.swing.JPanel {

    // Variables globales
    String path = "";

    /**
     * Cosntructor
     */
    public DifCultAvisosPanel() {
        initComponents();

        // 1. Dando formato al panel
        formatoInterfaz();
        
        // 2. Actualizando los datos de la tabla
        actualizarTabla();
    }

    /**
     * Da formayo al componente de tipo panel
     */
    private void formatoInterfaz() {
        Date sqlDate = new Date(System.currentTimeMillis());

        String pattern = "dd/MM/yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);

        jLabel_Fecha.setText(simpleDateFormat.format(sqlDate));

        jTable_Avisos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTextArea_Descr.setCaretPosition(0);
        jTextArea_Descr.setLineWrap(true);
        jTextArea_Descr.setWrapStyleWord(true);
    }

    /**
     * Actualiza los datos de la tabla
     */
    private void actualizarTabla() {
        try {
            Consultas.LlenarTablaAvisos(jTable_Avisos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar tabla", "", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Limpia los controles del formulario de alta
     */
    private void limpiarInterfaz() {
        jLabel_Fecha.setText("");
        jTextArea_Descr.setText("");
        jLabel_Imagen.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_Avisos = new javax.swing.JTabbedPane();
        jScrollPane_MostrarAvisos = new javax.swing.JScrollPane();
        jTable_Avisos = new javax.swing.JTable();
        jPanel_NuevoAviso = new javax.swing.JPanel();
        jLabel_Descripcion = new javax.swing.JLabel();
        jScrollPane_DescrNuevoAviso = new javax.swing.JScrollPane();
        jTextArea_Descr = new javax.swing.JTextArea();
        jLabel_Fecha = new javax.swing.JLabel();
        jLabel_Imagen = new javax.swing.JLabel();
        jButton_ElegirImagen = new javax.swing.JButton();
        jPanel_BannerNuevoAviso = new javax.swing.JPanel();
        jLabel_TituloFecha = new javax.swing.JLabel();
        jButton_GuardarAviso = new javax.swing.JButton();
        jLabel_TituloBannerNuevoAviso = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(683, 428));

        jTabbedPane_Avisos.setToolTipText("");
        jTabbedPane_Avisos.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jTable_Avisos.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTable_Avisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. aviso", "Descripción", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Avisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_AvisosMouseClicked(evt);
            }
        });
        jScrollPane_MostrarAvisos.setViewportView(jTable_Avisos);

        jTabbedPane_Avisos.addTab("Ver todos los avisos", jScrollPane_MostrarAvisos);

        jPanel_NuevoAviso.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_NuevoAviso.setLayout(null);

        jLabel_Descripcion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel_Descripcion.setText("Descripción");
        jPanel_NuevoAviso.add(jLabel_Descripcion);
        jLabel_Descripcion.setBounds(130, 120, 72, 15);

        jTextArea_Descr.setColumns(20);
        jTextArea_Descr.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextArea_Descr.setRows(5);
        jScrollPane_DescrNuevoAviso.setViewportView(jTextArea_Descr);

        jPanel_NuevoAviso.add(jScrollPane_DescrNuevoAviso);
        jScrollPane_DescrNuevoAviso.setBounds(130, 150, 290, 160);

        jLabel_Fecha.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel_Fecha.setText("[Fecha]");
        jPanel_NuevoAviso.add(jLabel_Fecha);
        jLabel_Fecha.setBounds(270, 90, 150, 15);

        jLabel_Imagen.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Imagen.setOpaque(true);
        jPanel_NuevoAviso.add(jLabel_Imagen);
        jLabel_Imagen.setBounds(450, 130, 180, 180);

        jButton_ElegirImagen.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jButton_ElegirImagen.setText("Elegir archivo");
        jButton_ElegirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ElegirImagenActionPerformed(evt);
            }
        });
        jPanel_NuevoAviso.add(jButton_ElegirImagen);
        jButton_ElegirImagen.setBounds(470, 90, 126, 29);

        jPanel_BannerNuevoAviso.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout jPanel_BannerNuevoAvisoLayout = new javax.swing.GroupLayout(jPanel_BannerNuevoAviso);
        jPanel_BannerNuevoAviso.setLayout(jPanel_BannerNuevoAvisoLayout);
        jPanel_BannerNuevoAvisoLayout.setHorizontalGroup(
            jPanel_BannerNuevoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel_BannerNuevoAvisoLayout.setVerticalGroup(
            jPanel_BannerNuevoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel_NuevoAviso.add(jPanel_BannerNuevoAviso);
        jPanel_BannerNuevoAviso.setBounds(0, 0, 80, 390);

        jLabel_TituloFecha.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel_TituloFecha.setText("Fecha de publicación:");
        jPanel_NuevoAviso.add(jLabel_TituloFecha);
        jLabel_TituloFecha.setBounds(130, 90, 131, 15);

        jButton_GuardarAviso.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jButton_GuardarAviso.setText("Guardar");
        jButton_GuardarAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarAvisoActionPerformed(evt);
            }
        });
        jPanel_NuevoAviso.add(jButton_GuardarAviso);
        jButton_GuardarAviso.setBounds(290, 330, 93, 40);

        jLabel_TituloBannerNuevoAviso.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel_TituloBannerNuevoAviso.setText("1. Llena los parámetros para dar de alta un aviso.");
        jPanel_NuevoAviso.add(jLabel_TituloBannerNuevoAviso);
        jLabel_TituloBannerNuevoAviso.setBounds(120, 20, 480, 23);

        jTabbedPane_Avisos.addTab("Nuevo aviso", jPanel_NuevoAviso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Avisos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Avisos, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        jTabbedPane_Avisos.getAccessibleContext().setAccessibleName("Nuevo aviso");
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Botón de elegir imagen
     * @param evt 
     */
    private void jButton_ElegirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ElegirImagenActionPerformed
        JFileChooser jfile = new JFileChooser();
        jfile.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG, and PNG Images", "jpg", "png");
        jfile.addChoosableFileFilter(filter);
        jfile.setFileFilter(filter);

        int resultado = jfile.showSaveDialog(null);

        if (resultado != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File archivoSelec = jfile.getSelectedFile();
        String nombreArch = archivoSelec.getName();

        if (nombreArch.endsWith(".jpg") || nombreArch.endsWith(".JPG") || nombreArch.endsWith(".png") || nombreArch.endsWith(".PNG")) {

            path = archivoSelec.getAbsolutePath();
            ImageIcon imagen = new ImageIcon(path);

            Image img = imagen.getImage();
            Image imagenAjustada = img.getScaledInstance(jLabel_Imagen.getWidth(), jLabel_Imagen.getHeight(), Image.SCALE_SMOOTH);

            ImageIcon imagenFinal = new ImageIcon(imagenAjustada);
            jLabel_Imagen.setIcon(imagenFinal);

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una imagen", "Intente de nuevo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton_ElegirImagenActionPerformed

    /**
     * Evento de la tabla de avisos
     * @param evt 
     */
    private void jTable_AvisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_AvisosMouseClicked
        // Evento de doble click
        if (evt.getClickCount() == 2) {
            // 1. Recupera la fila
            int row = jTable_Avisos.getSelectedRow();

            // 2. Recupero el ID del usuario
            int idAviso = (Integer) jTable_Avisos.getValueAt(row, 0);

            try {
                // 3. Consulto el aviso
                Aviso aviso = Consultas.consultarAviso(idAviso);

                // 4. Abro diálogo nuevo
                DlgAviso dialog = new DlgAviso(null, true, aviso);
                dialog.setVisible(true);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al consultar avisos: " + ex, "", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(DifCultAvisosPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable_AvisosMouseClicked

    /**
     * Botón de guardar
     * @param evt 
     */
    private void jButton_GuardarAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarAvisoActionPerformed
        if (path.equals("")) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una imagen", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(jTextArea_Descr.getText().equals("")){
            JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            Consultas.crearAviso(path, jTextArea_Descr.getText());
            JOptionPane.showMessageDialog(this, "Se ha guardado el registro", "", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "SError al guardar aviso", "", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DifCultAvisosPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        limpiarInterfaz();
        actualizarTabla();
    }//GEN-LAST:event_jButton_GuardarAvisoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ElegirImagen;
    private javax.swing.JButton jButton_GuardarAviso;
    private javax.swing.JLabel jLabel_Descripcion;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_Imagen;
    private javax.swing.JLabel jLabel_TituloBannerNuevoAviso;
    private javax.swing.JLabel jLabel_TituloFecha;
    private javax.swing.JPanel jPanel_BannerNuevoAviso;
    private javax.swing.JPanel jPanel_NuevoAviso;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane_DescrNuevoAviso;
    private javax.swing.JScrollPane jScrollPane_MostrarAvisos;
    private javax.swing.JTabbedPane jTabbedPane_Avisos;
    private javax.swing.JTable jTable_Avisos;
    private javax.swing.JTable jTable_Usuarios;
    private javax.swing.JTable jTable_Usuarios1;
    private javax.swing.JTable jTable_Usuarios2;
    private javax.swing.JTextArea jTextArea_Descr;
    // End of variables declaration//GEN-END:variables
}
