/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.SubAcademica;

import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Consultas;

/**
 *
 * @author mexen
 */
public class SubAcademicaPanel extends javax.swing.JPanel {

    /**
     * Creates new form Convenios
     */
    public SubAcademicaPanel() {
        initComponents();
         try {
            // TODO add your handling code here:
            Consultas.LlenarTabla_Convenios(Table_Convenios);
            Consultas.LlenarTabla_Formatos(Table_Formatos);
        } catch (Exception ex) {
            Logger.getLogger(SubAcademicaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabedPane_SubAca = new javax.swing.JTabbedPane();
        ScrollPane_ConveniosVig = new javax.swing.JScrollPane();
        Table_Convenios = new javax.swing.JTable();
        ScrollPane_Formatos = new javax.swing.JScrollPane();
        Table_Formatos = new javax.swing.JTable();

        setToolTipText("Formatos");

        TabedPane_SubAca.setToolTipText("");
        TabedPane_SubAca.setVerifyInputWhenFocusTarget(false);
        TabedPane_SubAca.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                TabedPane_SubAcaMouseWheelMoved(evt);
            }
        });
        TabedPane_SubAca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabedPane_SubAcaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabedPane_SubAcaMouseEntered(evt);
            }
        });

        Table_Convenios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Convenios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Table_ConveniosMousePressed(evt);
            }
        });
        ScrollPane_ConveniosVig.setViewportView(Table_Convenios);
        Table_Convenios.getAccessibleContext().setAccessibleName("Tabla_Convenios");

        TabedPane_SubAca.addTab("Convenios Vigentes", ScrollPane_ConveniosVig);

        Table_Formatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPane_Formatos.setViewportView(Table_Formatos);
        Table_Formatos.getAccessibleContext().setAccessibleName("Tabla_Formatos");

        TabedPane_SubAca.addTab("Formatos", ScrollPane_Formatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabedPane_SubAca, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabedPane_SubAca, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        TabedPane_SubAca.getAccessibleContext().setAccessibleName("TabbedPane_SubAcademica");

        getAccessibleContext().setAccessibleName("Formatos");
    }// </editor-fold>//GEN-END:initComponents

    private void TabedPane_SubAcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabedPane_SubAcaMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_TabedPane_SubAcaMouseEntered

    private void TabedPane_SubAcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabedPane_SubAcaMouseClicked

    }//GEN-LAST:event_TabedPane_SubAcaMouseClicked

    private void TabedPane_SubAcaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_TabedPane_SubAcaMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TabedPane_SubAcaMouseWheelMoved

    private void Table_ConveniosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ConveniosMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_Table_ConveniosMousePressed


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane_ConveniosVig;
    private javax.swing.JScrollPane ScrollPane_Formatos;
    private javax.swing.JTabbedPane TabedPane_SubAca;
    private javax.swing.JTable Table_Convenios;
    private javax.swing.JTable Table_Formatos;
    // End of variables declaration//GEN-END:variables
}
